"""Setup script for Newsauto package."""

from setuptools import setup, find_packages

setup(
    name="newsauto",
    version="0.1.0",
    description="Automated newsletter platform using local LLMs",
    author="Durant Bros",
    packages=find_packages(),
    python_requires=">=3.12",
    install_requires=[
        "fastapi==0.109.0",
        "uvicorn[standard]==0.27.0",
        "sqlalchemy==2.0.25",
        "alembic==1.13.1",
        "pydantic==2.5.3",
        "pydantic-settings==2.1.0",
        "httpx==0.25.2",
        "python-multipart==0.0.6",
        "python-jose[cryptography]==3.3.0",
        "passlib[bcrypt]==1.7.4",
        "feedparser==6.0.10",
        "beautifulsoup4==4.12.2",
        "torch>=2.1.2",
        "transformers==4.37.0",
        "sentence-transformers==2.3.1",
        "ollama==0.1.6",
        "praw==7.7.1",
        "aiohttp==3.9.1",
        "jinja2==3.1.3",
        "emails==0.6",
        "lxml==5.1.0",
        "nltk==3.9.1",
        "spacy==3.7.2",
        "scikit-learn==1.4.0",
        "numpy<2.0",
        "pandas==2.1.4",
        "celery==5.3.4",
        "redis==5.0.1",
        "cryptography==41.0.7",
        "python-dotenv==1.0.0",
        "structlog==24.1.0",
        "asyncpg==0.29.0",
        "rich==13.7.0",
        "typer==0.9.0",
        "click==8.1.7",
        "Pillow==10.2.0",
        "requests==2.31.0",
        "aiosmtplib==3.0.1",
        "html2text==2024.2.26",
        "premailer==3.10.0",
        "pytz==2024.1",
        "croniter==2.0.1",
        "json5==0.9.14",
        "prometheus-client==0.19.0",
        "psutil==5.9.7",
        "scipy>=1.16.0",
    ],
    extras_require={
        "dev": [
            "pytest==8.4.2",
            "pytest-cov==7.0.0",
            "pytest-asyncio==1.2.0",
            "black==25.9.0",
            "ruff==0.13.1",
            "mypy==1.18.2",
        ]
    },
    entry_points={
        "console_scripts": [
            "newsauto=newsauto.cli:main",
        ],
    },
)
