blank_issues_enabled: true
contact_links:
  - name: Newsauto Discussions
    url: https://github.com/dttb-capy/Newsauto/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/dttb-capy/Newsauto/blob/main/README.md
    about: Read the project documentation
