name: Daily Newsletter Automation

on:
  schedule:
    # Run at 9 AM EST (2 PM UTC) every weekday
    - cron: '0 14 * * 1-5'
  workflow_dispatch:  # Allow manual trigger

jobs:
  generate-newsletters:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Ollama
      run: |
        curl -fsSL https://ollama.com/install.sh | sudo -E sh
        ollama serve &
        sleep 5
        ollama pull mistral:7b-instruct || ollama pull mistral:latest

    - name: Run newsletter pipeline
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SMTP_HOST: ${{ secrets.SMTP_HOST }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        SMTP_USE_TLS: true
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        OLLAMA_HOST: http://localhost:11434
      run: |
        python -m newsauto.automation.full_pipeline

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: newsletter-logs
        path: logs/

  notify-results:
    needs: generate-newsletters
    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: Send notification
      run: |
        if [ "${{ needs.generate-newsletters.result }}" == "success" ]; then
          echo "✅ Daily newsletters sent successfully"
        else
          echo "❌ Newsletter generation failed - check logs"
        fi